### ISSUE TITLE
Gatsby V4, links for pages don't work on normal browsing but work in incognito mode, devtool and dev/serve mode

### ISSUE THREAD

**Issue by AnnieTaylorCHEN** [gatsbyjs/gatsby#34251]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

**UPDATE:** the below issue disappears if I do hard reload on Chrome. But after some time it comes back. So I would like to know what's causing this error to see if I can do anything about it. 

It started to appear after I upgraded to V4 a while ago. Mostly single blog page would work everywhere. The ones that don't work well are the ones that are pages, including the pages like `/tags/food`, particularly those in the navigation. 

Links worked fine in `gatsby dev `and `gatsby serve`, exactly as expected. After deployed to Netlify, I've also tested them both in Chrome and Firefox. They worked perfectly when you have "inspect" dev tool open, or in incognito or private mode. So in all, it works 

- dev / serve in local development 
- inspect dev tool mode 
- incognito mode 
- when you open the link in another tab 

The only time it doesn't work is when you just browse normally.... it would either load a blank page (if you refresh it would of course load fine again), or doesn't do anything at all. And the console error is often like this:
```
Uncaught TypeError: l.ZP.loadPage(...).then is not a function
    at w (121855582369c7d8b0d63076256c0559e31c8137.js:1)
    at window.___navigate (121855582369c7d8b0d63076256c0559e31c8137.js:1)
    at Object.onClick (121855582369c7d8b0d63076256c0559e31c8137.js:1)
    at onClick (121855582369c7d8b0d63076256c0559e31c8137.js:1)
    at Object.o (121855582369c7d8b0d63076256c0559e31c8137.js:1)
    at p (121855582369c7d8b0d63076256c0559e31c8137.js:1)
    at 121855582369c7d8b0d63076256c0559e31c8137.js:1
    at g (121855582369c7d8b0d63076256c0559e31c8137.js:1)
    at ot (121855582369c7d8b0d63076256c0559e31c8137.js:1)
    at it (121855582369c7d8b0d63076256c0559e31c8137.js:1)
```
Since I am not sure this could be reproduced properly with minimal production, I can't provide one as it might just work? 

### Reproduction Link

https://www.petiteandminimal.com/

### Steps to Reproduce

1. Just go to my site and browse as usual and if you experience problems above. 
2. If so, try again in incognito mode and see if problem disappeared. 

### Expected Result

Links should work as usual, when you click on something it leads you to the new page. 

### Actual Result

Links as pages or /tags/food etc don't work properly sometimes. 

### Environment

```shell
System:
    OS: Linux 5.4 Linux Mint 20 (Ulyana)
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 8.1.1 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Browsers:
    Chrome: 96.0.4664.93
    Firefox: 95.0
  npmPackages:
    gatsby: ^4.0.0 => 4.0.0 
    gatsby-image: ^2.3.5 => 2.11.0 
    gatsby-plugin-algolia: ^0.22.2 => 0.22.2 
    gatsby-plugin-google-gtag: ^4.1.0-next.0 => 4.1.0-next.0 
    gatsby-plugin-html-attributes: ^1.0.5 => 1.0.5 
    gatsby-plugin-image: ^2.1.0-next.0 => 2.1.0-next.0 
    gatsby-plugin-manifest: ^4.1.0-next.0 => 4.1.0-next.0 
    gatsby-plugin-offline: ^5.1.0-next.0 => 5.1.0-next.0 
    gatsby-plugin-react-helmet: ^5.1.0-next.0 => 5.1.0-next.0 
    gatsby-plugin-remove-fingerprints: 0.0.2 => 0.0.2 
    gatsby-plugin-robots-txt: ^1.5.6 => 1.5.6 
    gatsby-plugin-sharp: ^4.1.0-next.0 => 4.1.0-next.0 
    gatsby-plugin-sitemap: ^5.1.0-next.0 => 5.1.0-next.0 
    gatsby-plugin-styled-components: ^5.1.0-next.0 => 5.1.0-next.0 
    gatsby-remark-images: ^6.1.0-next.0 => 6.1.0-next.0 
    gatsby-source-filesystem: ^4.1.0-next.0 => 4.1.0-next.0 
    gatsby-transformer-remark: ^5.1.0-next.0 => 5.1.0-next.0 
    gatsby-transformer-sharp: ^4.1.0-next.0 => 4.1.0-next.0
```

### Config Flags

NO

**Comment by graysonhicks** [comment]
Hi @AnnieTaylorCHEN, I just tried the site in both regular and incognito mode.  I clicked approximately 50 links from both /tags/food and /tags/style as well as clicking around the site and was unable to reproduce the problem.

**Comment by AnnieTaylorCHEN** [comment]
> Hi @AnnieTaylorCHEN, I just tried the site in both regular and incognito mode. I clicked approximately 50 links from both /tags/food and /tags/style as well as clicking around the site and was unable to reproduce the problem.

I also tried "clear cache" on Chrome today, and after that it seems everything works well, and I haven't seen the error so far. However, I haven't done this on Firefox, so I just managed to record a session so I can show it. Does it have something to do with browser's cache?!

https://user-images.githubusercontent.com/25988475/146069897-095d7a87-30e7-4dc0-83dc-98f3d84ed687.mp4

**Comment by AnnieTaylorCHEN** [comment]
I am a bit concerned if the end user doesn't do clear cache or if they doesn't even know how to do "hard reload", and if they're a regular visitor of the site (like me, who has old cache there in their browser), they might perceive the above situation as errors. So what can I do to make sure whenever I have a new site update (git push connected on Netlify), all the local cache should delete their old one or do something similar so it doesn't have such error?

**Comment by rjoonas** [comment]
Seeing this issue in production as well on Gatsby 4.10.0. Clicking a link doesn't do anything at all and throws this exception. I wonder if error handling could be improved here to do a dumb navigation to the link target URL even if Gatsby's navigation throws?

**Comment by mikaelbang** [comment]
Same here!

**Comment by AnnieTaylorCHEN** [comment]
Yeah... today I checked my site and the issue remains.

**Comment by graysonhicks** [comment]
I tried to reproduce again on @AnnieTaylorCHEN's site and am still unable to.  Can others who see this post steps to reproduce?  Posting context and relevant information would be helpful, thanks!

**Comment by AnnieTaylorCHEN** [comment]
@graysonhicks 
As others said, this one is a bit difficult to reproduce. 

Yesterday I have done exactly like before, I cleared all my chrome cache, and restarted it and everything functions as normal again. I kept my firefox "uncleared", and the problem remains like the above video. 

If you don't mind, save my website as a bookmark, browse it a few times a week or just leave it be. After a few weeks/months, before you clear your cache, come back and test again, you might encounter the issue we mentioned above. 

By the way, I haven't upgraded to the latest, so I am still having 4.0.0. But @rjoonas mentioned he sees this in 4.10.0 also, which probably means the issue wasn't addressed since 4. I will keep my version for now so at least we have a specimen of 4.0.0 for testing purpose.

**Comment by mikaelbang** [comment]
@AnnieTaylorCHEN

**Comment by AnnieTaylorCHEN** [comment]
@mikaelbang 
Interesting here [https://www.gatsbyjs.com/plugins/gatsby-plugin-remove-fingerprints/](https://www.gatsbyjs.com/plugins/gatsby-plugin-remove-fingerprints/):

> services like [Netlify](https://netlify.com/) recommend building files without a hash. This plugin will eliminate the hash from built JavaScript files.

I'm using Netlify for this project. Maybe that's why. I just did a push now and will tested on my firefox and report back.

**Comment by mikaelbang** [comment]
@AnnieTaylorCHEN 

Yes we had the same setup with Netlify, and then noticed that error randomly. Seems to be fixed when we removed the plugin :)

**Comment by AnnieTaylorCHEN** [comment]
@mikaelbang 

Wow this did that magic. I just published and tested it on my firefox (old cache no clearing) and now it works as expected. 
@rjoonas @trivedip you can perhaps give it a try too (I assume if you have similar setting that is).

**Comment by graysonhicks** [comment]
Thanks @mikaelbang !

**Comment by yoonjuh** [comment]
Does anyone still having this issue? 

My app is 
- Not on Netlify
- Not using [gatsby-plugin-remove-fingerprints/](https://www.gatsbyjs.com/plugins/gatsby-plugin-remove-fingerprints/) 
- using gatsby@4.17.2
 
But I am still seeing this error in the production logs and I am not able to reproduce it. If any has other suggestion or good understanding of this issue, Please share your insight on this. Thank you in advance!
