### ISSUE TITLE
gatsby-cli cannot find module 'detect-port' after upgrading to latest version 2.12.31

### ISSUE THREAD

**Issue by ruiehq** [gatsbyjs/gatsby#24326]
## Description

Everything is working smoothly with my cli but after bumping up my version to 2.12.31, my getting this error now. I tried downgrading to my previous version but still no luck.

### Steps to reproduce

```
npm install -g gatsby-cli
```

### Expected result

Upgraded to new version.

### Actual result

```
C:\Users\reuiqh\AppData\Roaming\npm\node_modules\gatsby-cli\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

Error: Cannot find module 'detect-port'
Require stack:
- C:\Users\vdelapena\AppData\Roaming\npm\node_modules\gatsby-cli\lib\recipes.js
- C:\Users\vdelapena\AppData\Roaming\npm\node_modules\gatsby-cli\lib\create-cli.js
- C:\Users\vdelapena\AppData\Roaming\npm\node_modules\gatsby-cli\lib\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\vdelapena\AppData\Roaming\npm\node_modules\gatsby-cli\lib\recipes.js:18:42)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\vdelapena\\AppData\\Roaming\\npm\\node_modules\\gatsby-cli\\lib\\recipes.js',
    'C:\\Users\\vdelapena\\AppData\\Roaming\\npm\\node_modules\\gatsby-cli\\lib\\create-cli.js',
    'C:\\Users\\vdelapena\\AppData\\Roaming\\npm\\node_modules\\gatsby-cli\\lib\\index.js'
  ]
}
```

### Environment
Even if I run gatsby info --clipboard command, the same error pops up.

Windows 10
Node version = 13.8.0
NPM version = 6.13.6

Sorry for limited info. I'm trying everything to bring back cli

**Comment by sesteva** [comment]
+1 
Same exact error
macOS 10.14.6
node v14.3.0
yarn version v1.22.4

**Comment by cesutherland** [comment]
Me too!

```
$ node --version
v10.18.0
carl@solo6 ~/Projects
$ npm --version
6.13.4
```

```
$ gatsby
/home/carl/.nvm/versions/node/v10.18.0/lib/node_modules/gatsby-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53                                            
        throw ex;                                                                                                                                                                     
        ^                                                                                                                                                                             
                                                                                                                                                                                      
Error: Cannot find module 'detect-port'                                                                                                                                               
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)                                                                                                       
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)                                                                                                                  
    at Module.require (internal/modules/cjs/loader.js:692:17)                                                                                                                         
    at require (internal/modules/cjs/helpers.js:25:18)                                                                                                                                
    at Object.<anonymous> (/home/carl/.nvm/versions/node/v10.18.0/lib/node_modules/gatsby-cli/lib/recipes.js:18:42)                                                                   
    at Module._compile (internal/modules/cjs/loader.js:778:30)                                                                                                                        
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)                                                                                                          
    at Module.load (internal/modules/cjs/loader.js:653:32)                                                                                                                            
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)                                                                                                                          
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by mitchellbusby** [comment]
I think this is the same as my issue (#24325)

**Comment by ruiehq** [comment]
Yeah that's right. BTW, have you fix this issue by installing detect-port manually?

**Comment by ruiehq** [comment]
Duplicate of #24325

**Comment by mitchellbusby** [comment]
Sorry for missing your comment @ruiehq -- the answer was yes that installing manually does work :)

**Comment by mcljs** [comment]
Tambien tengo el mismo problema
