### ISSUE TITLE
How to disable React error overlay?

### ISSUE THREAD

**Issue by nolandg** [gatsbyjs/gatsby#20420]
I find the `react-error-overlay` useless because the same info and stack trace is in my console and the error overlay is super slow and blocking browser UI as it loads the stack traces. How do I disable it?

I have tried:
````js
// gatsby-browser.js
import { setConfig } from 'react-hot-loader';

setConfig({ ErrorOverlay: () => null });

window.addEventListener('error', (e) => {
  e.stopImmediatePropagation();
  e.preventDefault();
});
````

which was supposed to work? but does nothing.

Any thoughts? Thanks!

**Comment by nolandg** [comment]
Ok, I have a workable solution now. And it sure makes debugging errors snappier without this overlay. Chrome dev tools was bogging for many seconds parsing the sources lines etc. and totally blocking debugger UI and my OS.

I created a folder in my project `react-error-overlay` and the `index.js` file in there exports all the required functions and does nothing:
````js
module.exports = {
  setEditorHandler: () => { },
  reportBuildError: () => { },
  reportRuntimeError: () => { },
  dismissBuildError: () => { },
  startReportingRuntimeErrors: () => {},
  dismissRuntimeErrors: () => { },
  stopReportingRuntimeErrors: () => { },
};
````
and pointed the Gatsby webpack alias plugin there:
````js
// gatsby-config.js
plugins: [
    {
      resolve: 'gatsby-plugin-root-import',
      options: {
        src: path.join(__dirname, 'src'),
        '~': path.join(__dirname),
        'react-error-overlay': path.join(__dirname, 'your-project/react-error-overlay'),
      },
    },
]
````

After clearing the cache and restarting it took this file instead and now doesn't bog on every error.

**Comment by maciejmyslinski** [comment]
@nolandg that's helpful although hot reloading stops working when there is an error detected 😢

**Comment by maciejmyslinski** [comment]
👌 I had to remove `eslint-loader` from webpack config
```js
exports.onCreateWebpackConfig = ({ actions, getConfig }) => {
  // prevent gatsby build failing on eslint errors
  const defaultConfig = getConfig();
  defaultConfig.module.rules = defaultConfig.module.rules.filter(
    rule => rule.loader !== 'eslint-loader'
  );
  actions.replaceWebpackConfig(defaultConfig);
}
```

**Comment by pedroBruno7** [comment]
@nolandg Thanks a lot for the issue, very relevant
In my case it's not working on "gatsby": "^3.9.0". I get the following error during gatsby develop:

```
There was an error compiling the html.js component for the development server.
See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html TypeError: (0 , graphql__WEBPACK_IMPORTED_MODULE_0__.parse) is not a
function
 WebpackError: TypeError: (0 , graphql__WEBPACK_IMPORTED_MODULE_0__.parse) is not a function
```

  "gatsby": "^3.9.0",
  "gatsby-plugin-root-import": "^2.0.8",
  "graphql": "^15.5.0",
  "react": "17.0.2",
  "react-dom": "17.0.2",

Does anyone have a solution? Thank you

**Comment by pedroBruno7** [comment]
I think I found a good CSS only solution to disable the error overlay (the modal) on gatsby. [This](https://github.com/facebook/create-react-app/pull/9342) does not work because on gatsby the html is completely different

I added to my global css:

`gatsby-fast-refresh {
  display: none !important;
}

body {
  padding: 0 !important;
  overflow: auto !important;
}`

For my goal it was perfect. I wanted to not display the error overlay when the error was caught by an Error Boundary. With this CSS solution, the overlay will not appear when the Error Boundary catches the error, but when there is no Error Boundary, the screen goes full white, alerting the developer there is an error
