### PR TITLE
updates serve to version 9.2.0 #6546

### PR DESCRIPTION
**Pull request by franz899**
Updates `serve` dependency to version 9.2.0. #6546

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 84840c1bcf4f959c33f412c69ed96fe5671d0637

https://app.netlify.com/sites/using-postcss-sass/deploys/5b50d23c4ed62f2d9ac85d7e

**Comment by KyleAMathews** [comment]
Deploy preview for *using-glamor* failed.

Built with commit 84840c1bcf4f959c33f412c69ed96fe5671d0637

https://app.netlify.com/sites/using-glamor/deploys/5b50d23c4ed62f2d9ac85d84

**Comment by KyleAMathews** [comment]
@franz899 can you make the same PR to the `v1` branch so we can release it there as well?

**Comment by franz899** [comment]
@KyleAMathews Sure 😄

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by Raincal** [comment]
@KyleAMathews `gatsby serve` does't work in gatsby@2.0.0-beta.48

error There was a problem loading the local serve command. Gatsby may not be installed. Perhaps you need to run "npm install"?


  Error: Cannot find module 'serve'

  - loader.js:581 Function.Module._resolveFilename
    internal/modules/cjs/loader.js:581:15

  - loader.js:507 Function.Module._load
    internal/modules/cjs/loader.js:507:25

  - loader.js:637 Module.require
    internal/modules/cjs/loader.js:637:17

  - helpers.js:20 require
    internal/modules/cjs/helpers.js:20:18

  - serve.js:4 Object.<anonymous>
    [gatsby-starter-default]/[gatsby]/dist/commands/serve.js:4:15

  - loader.js:689 Module._compile
    internal/modules/cjs/loader.js:689:30

  - loader.js:700 Object.Module._extensions..js
    internal/modules/cjs/loader.js:700:10

  - loader.js:599 Module.load
    internal/modules/cjs/loader.js:599:32

  - loader.js:538 tryModuleLoad
    internal/modules/cjs/loader.js:538:12

  - loader.js:530 Function.Module._load
    internal/modules/cjs/loader.js:530:3

  - loader.js:637 Module.require
    internal/modules/cjs/loader.js:637:17

  - helpers.js:20 require
    internal/modules/cjs/helpers.js:20:18

  - create-cli.js:49 resolveLocalCommand
    [gatsby-starter-default]/[gatsby]/[gatsby-cli]/lib/create-cli.js:49:14

  - create-cli.js:64 Object.argv [as handler]
    [gatsby-starter-default]/[gatsby]/[gatsby-cli]/lib/create-cli.js:64:22

  - command.js:235 Object.runCommand
    [gatsby-starter-default]/[yargs]/lib/command.js:235:44

  - yargs.js:1046 Object.parseArgs [as _parseArgs]
    [gatsby-starter-default]/[yargs]/yargs.js:1046:30

**Comment by KyleAMathews** [comment]
@Raincal I just tried upgrading and it worked as expected. Perhaps there was an NPM install error? Try deleting `node_modules` and reinstalling.

**Comment by Raincal** [comment]
@KyleAMathews I tried many times even in my DigitalOcean VPS and it didn't work.
But it works ok in 2.0.0-beta.47.
### Steps to reproduce
```bash
gatsby new my-default-project https://github.com/gatsbyjs/gatsby-starter-default\#v2
cd my-default-project
npm run build
gatsby serve # Or add "serve": "gatsby serve" to package.json and run npm run serve
```

**Comment by KyleAMathews** [comment]
Yeah, looks like you're right @Raincal — @tryvsadmin looked up the breaking changes https://github.com/gatsbyjs/gatsby/commit/69125ccb5604830f6b11996ff3f6dddbe6fe0260#commitcomment-29773740

Not sure now why my update didn't uncover this.
