### PR TITLE
Start Recipes GraphQL server during gatsby develop

### PR DESCRIPTION
**Pull request by mxstbr**
This uses the service discovery mechanism introduced in #22759 to idempotently start the recipes GraphQL server during `gatsby develop`. That means if somebody runs `gatsby recipes` while they are already developing their site it will be _much_ faster.

This is also an important step along the way to Admin, which will query the same GraphQL server while develop is running. (reference draft PR: #23734)

### CODE REVIEW

**Comment by mxstbr** [comment]
The only failing CI is "Cloud Tests", which fail with this error:

```
Error: Cannot find module 'gatsby-recipes/dist/graphql-server'
```

This makes no sense because this module exists, a) I can see it locally but more importantly b) all other tests (including those touching the same code paths) pass! 🤔 

Does anybody have an idea why this happens?

File: packages/gatsby-cli/src/recipes.ts [hunk 1]
```diff
@@ -1,59 +1,19 @@
 import { trackCli } from "gatsby-telemetry"
-import execa from "execa"
-import * as path from "path"
-import * as fs from "fs"
-import detectPort from "detect-port"
+// NOTE(@mxstbr): I explicitly import from /index because the file used to live at graphql.js, which means developers with old builds on their local machines will have that old version imported instead of the new one with changes
+import startGraphQLServer from "gatsby-recipes/dist/graphql-server"
```
Comment (freiksenet) [inline packages/gatsby-cli/src/recipes.ts:3]: This should be a normal export for gatsby-recipes, not internal one.

File: packages/gatsby-cli/src/recipes.ts [hunk 2]
```diff
@@ -1,59 +1,19 @@
 import { trackCli } from "gatsby-telemetry"
-import execa from "execa"
-import * as path from "path"
-import * as fs from "fs"
-import detectPort from "detect-port"
+// NOTE(@mxstbr): I explicitly import from /index because the file used to live at graphql.js, which means developers with old builds on their local machines will have that old version imported instead of the new one with changes
```
Comment (laurieontech) [inline packages/gatsby-cli/src/recipes.ts:2]: Outdated comment?

File: packages/gatsby-recipes/src/graphql-server/index.js [hunk 3]
```diff
@@ -0,0 +1,56 @@
+import execa from "execa"
+import * as path from "path"
+import * as fs from "fs"
+import detectPort from "detect-port"
+import {
+  getService,
+  createServiceLock,
+} from "gatsby-core-utils/dist/service-lock"
+
+// NOTE(@mxstbr): The forceStart boolean enforces us to start the recipes graphql server
```
Comment (freiksenet) [inline packages/gatsby-recipes/src/graphql-server/index.js:10]: Could this result in having two separate recipe servers running?

File: packages/gatsby/src/commands/develop.ts [hunk 4]
```diff
@@ -124,6 +125,7 @@ module.exports = async (program: IProgram): Promise<void> => {
     programPath: program.directory,
   })
 
+  await startGraphQLServer(program.directory, true)
```
Comment (freiksenet) [inline packages/gatsby/src/commands/develop.ts:128]: I don't think develop should start recipes server, rather it should be the wrapper. You don't need to wait for develop to run. It will also allow us to not depend on `gatsby-recipes`.

Comment (mxstbr) [reply packages/gatsby/src/commands/develop.ts:128]: This is the wrapper :blush:

File: packages/gatsby-recipes/src/graphql-server/index.js (hunk 3 above)
Comment (mxstbr) [reply packages/gatsby-recipes/src/graphql-server/index.js:10]: Yes, but that's fine temporarily I think. cc @johno for confirmation

File: packages/gatsby/src/commands/develop.ts (hunk 4 above)
Comment (freiksenet) [reply packages/gatsby/src/commands/develop.ts:128]: Yeah, got it. Now I think that it should be outside of Gatsby.

File: packages/gatsby-recipes/src/index.js [hunk 5]
```diff
@@ -1,7 +1,7 @@
-exports.startGraphQLServer = require(`./graphql-server`).startGraphQLServer
-
 // data = { recipe?: string, graphqlPort: number, projectRoot: string }
 module.exports = async data => {
   const cli = require(`import-jsx`)(require.resolve(`./cli`))
   return cli(data)
 }
+
+module.exports.startGraphQLServer = require(`./graphql-server`).startGraphQLServer
```
Comment (ascorbic) [inline packages/gatsby-recipes/src/index.js:7]: Is this legal commonjs? You're effectively making startGraphQLServer a static property of the cli function

Comment (ascorbic) [reply packages/gatsby-recipes/src/index.js:7]: Are we able to refactor this to make the cli a default export (and maybe even make it an es module or TypeScript)? Where is it imported?

File: packages/gatsby-recipes/src/index.js [hunk 6]
```diff
@@ -1,4 +1,7 @@
-module.exports = recipe => {
+export { startGraphQLServer } from "./graphql-server"
+
+// data = { recipe?: string, graphqlPort: number, projectRoot: string }
+export default async data => {
```
Comment (ascorbic) [inline packages/gatsby-recipes/src/index.js:4]: This is great, but could you turn this into a named function rather than an anonymous arrow. You can still make it a default export, but it means it's easier to profile. This is a request from @pvdz for all exports to be named.

File: packages/gatsby-cli/src/recipes.ts [hunk 7]
```diff
@@ -1,59 +1,17 @@
 import { trackCli } from "gatsby-telemetry"
-import execa from "execa"
-import * as path from "path"
-import * as fs from "fs"
-import detectPort from "detect-port"
+import runRecipe, { startGraphQLServer } from "gatsby-recipes"
```
Comment (KyleAMathews) [inline packages/gatsby-cli/src/recipes.ts:2]: not really related to this PR but is there a way with the lock stuff to run a service in the foreground? Sometimes that's convenient to directly see the logs or to run the service with the node debugger.

File: packages/gatsby-recipes/src/graphql-server/index.js [hunk 8]
```diff
@@ -0,0 +1,54 @@
...
+const fs = require(`fs`)
+const detectPort = require(`detect-port`)
+const {
+  getService,
+  createServiceLock,
+} = require(`gatsby-core-utils/dist/service-lock`)
+
+// NOTE(@mxstbr): The forceStart boolean enforces us to start the recipes graphql server
+// even if another instance might already be running. This is necessary to ensure the gatsby
+// develop command does not _not_ run the server if the user is running gatsby recipes at the same time.
```
[the remark this answers is not in the document]
Comment (mxstbr) [reply packages/gatsby-recipes/src/graphql-server/index.js:12]: It does not _not_ run the server (two nots!). Basically, it just starts the server anyway :wink:

File: packages/gatsby-cli/src/recipes.ts (hunk 7 above)
Comment (mxstbr) [reply packages/gatsby-cli/src/recipes.ts:2]: Yeah totally, _how_ you run your service is completely up to you 👍

File: packages/gatsby-recipes/src/graphql-server/index.js (hunk 3 above)
Comment (mxstbr) [reply packages/gatsby-recipes/src/graphql-server/index.js:10]: Confirmed by johno in Slack!

**Comment by freiksenet** [comment]
:shipit:
