### ISSUE TITLE
Error on `gatsby develop`: `emitter.onAny is not a function`

### ISSUE THREAD

**Issue by danoc** [gatsbyjs/gatsby#2765]
I need to investigate further, but opening this issue in case there is a regression from https://github.com/gatsbyjs/gatsby/pull/2763:

```
$ gatsby develop
Options:
  -h, --help     Show help                                                                                                                                                                                                          [boolean]
  --verbose      Turn on verbose output                                                                                                                                                                            [boolean] [default: false]
  -H, --host     Set host. Defaults to localhost                                                                                                                                                              [string] [default: "localhost"]
  -p, --port     Set port. Defaults to 8000                                                                                                                                                                        [string] [default: "8000"]
  -o, --open     Open the site in your browser for you.                                                                                                                                                                             [boolean]
  -v, --version  Show version number                                                                                                                                                                                                [boolean]

error There was a problem loading the local develop command. Gatsby may not be installed.


  TypeError: emitter.onAny is not a function

  - index.js:59 Object.<anonymous>
    [www]/[gatsby]/dist/redux/index.js:59:9

  - module.js:20 require
    internal/module.js:20:19

  - webpack.config.js:55 Object.<anonymous>
    [www]/[gatsby]/dist/utils/webpack.config.js:55:16

  - module.js:20 require
    internal/module.js:20:19


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This is the affected line:

https://github.com/gatsbyjs/gatsby/blob/bff0cd377359ad1432a1da042349793096cb8d37/packages/gatsby/src/redux/index.js#L65-L67

May be related to this PR from 2 hours ago: https://github.com/gatsbyjs/gatsby/pull/2763

**Comment by jquense** [comment]
arg sorry, fix incoming

**Comment by danoc** [comment]
Fix appears to be almost done but anyone stuck can use `gatsby@1.9.93` for the time being.

**Comment by njosefbeck** [comment]
After the update the above error went away, but now it's saying that "del" can't be found when I run either `gatsby develop` or `gatsby build`.

**Comment by KyleAMathews** [comment]
Thanks @njosefbeck https://github.com/gatsbyjs/gatsby/pull/2767 should fix that

**Comment by KyleAMathews** [comment]
1.9.96 is out

**Comment by njosefbeck** [comment]
Now I'm getting the following error: `Cannot find module 'parse-passwd'` when trying to run "gatsby build".

**Comment by KyleAMathews** [comment]
Hmm I created a site from the default starter and ran develop/build/serve and all completed successfully.

**Comment by njosefbeck** [comment]
It's also building just fine for me locally, but then the deployment fails when I push it up to Netlify. Trying to work with them to see if it's an issue on their end...

<img width="1148" alt="screen shot 2017-11-02 at 5 48 25 pm" src="https://user-images.githubusercontent.com/9508002/32354081-200f437a-bff6-11e7-9aa6-a7d65af20033.png">

**Comment by njosefbeck** [comment]
So I fixed that issue by `yarn add`-ing parse-passwd to my project. Then when I deployed to Netlify everything worked just fine!

**Comment by jquense** [comment]
I wonder if that's netlify ignoring optional deps again...

**Comment by danoc** [comment]
The issue has been fixed for me. Feel free to close if you'd like. Unsure if the follow-up conversations are related.

**Comment by KyleAMathews** [comment]
👍  thanks for following up!
