### ISSUE TITLE
Error: Cannot find module './event-storage.js'

### ISSUE THREAD

**Issue by esetnik** [gatsbyjs/gatsby#16293]
## Description

Cannot install `gatsby-cli`

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

```bash
❯ npm install -g gatsby-cli
/Users/ethan/.nvm/versions/node/v10.16.1/bin/gatsby -> /Users/ethan/.nvm/versions/node/v10.16.1/lib/node_modules/gatsby-cli/lib/index.js

> core-js@2.6.9 postinstall /Users/ethan/.nvm/versions/node/v10.16.1/lib/node_modules/gatsby-cli/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> gatsby-telemetry@1.1.8 postinstall /Users/ethan/.nvm/versions/node/v10.16.1/lib/node_modules/gatsby-cli/node_modules/gatsby-telemetry
> node src/postinstall.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './event-storage.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/ethan/.nvm/versions/node/v10.16.1/lib/node_modules/gatsby-cli/node_modules/gatsby-telemetry/src/postinstall.js:2:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-telemetry@1.1.8 postinstall: `node src/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gatsby-telemetry@1.1.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ethan/.npm/_logs/2019-08-01T15_27_39_118Z-debug.log
```

### Expected result

No error

### Actual result
Error: Cannot find module './event-storage.js'

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
```bash
❯ gatsby info --clipboard
zsh: command not found: gatsby
```

**Comment by geocine** [comment]
Was supposed to open this issue, I am also encountering this just now, I get the same installation error. I am running the following command to start a new project.
```
yarn add gatsby react react-dom
```

**Comment by esetnik** [comment]
Workaround I found for now is to force `gatsby-telemetry@1.1.7`.

```bash
❯ npm install -g gatsby-cli@2.7.22 gatsby-telemetry@1.1.7
```

**Comment by ehowey** [comment]
Getting this error as well...same scenario as above.  Just commenting to bring visibility.  Happening on Netlify deploy log.

```
9:37:18 AM: Build ready to start
9:37:20 AM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
9:37:20 AM: build-image tag: v3.3.2
9:37:20 AM: buildbot version: ef8d0929ed0baabafd8bbb7d0b021e1fc24180c0
9:37:20 AM: Fetching cached dependencies
9:37:20 AM: Starting to download cache of 164.3MB
9:37:22 AM: Finished downloading cache in 1.591972698s
9:37:22 AM: Starting to extract cache
9:37:29 AM: Finished extracting cache in 7.17767497s
9:37:29 AM: Finished fetching cache in 8.8390278s
9:37:29 AM: Starting to prepare the repo for build
9:37:30 AM: Preparing Git Reference refs/heads/master
9:37:30 AM: Starting build script
9:37:30 AM: Installing dependencies
9:37:31 AM: Started restoring cached node version
9:37:36 AM: Finished restoring cached node version
9:37:36 AM: v10.16.1 is already installed.
9:37:38 AM: Now using node v10.16.1 (npm v6.9.0)
9:37:38 AM: Attempting ruby version 2.6.2, read from environment
9:37:39 AM: Using ruby version 2.6.2
9:37:40 AM: Using PHP version 5.6
9:37:40 AM: Started restoring cached node modules
9:37:40 AM: Finished restoring cached node modules
9:37:40 AM: Started restoring cached yarn cache
9:37:40 AM: Finished restoring cached yarn cache
9:37:41 AM: Installing NPM modules using Yarn version 1.13.0
9:37:41 AM: yarn install v1.13.0
9:37:41 AM: warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
9:37:41 AM: [1/4] Resolving packages...
9:37:47 AM: [2/4] Fetching packages...
9:38:13 AM: info fsevents@1.2.9: The platform "linux" is incompatible with this module.
9:38:13 AM: info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
9:38:13 AM: [3/4] Linking dependencies...
9:38:13 AM: warning "gatsby-theme-catalyst-onepage > gatsby-theme-catalyst-core > gatsby-plugin-theme-ui@0.2.25" has incorrect peer dependency "theme-ui@^0.1.2".
9:38:29 AM: [4/4] Building fresh packages...
9:38:30 AM: error /opt/build/repo/node_modules/gatsby-telemetry: Command failed.
9:38:30 AM: Exit code: 1
9:38:30 AM: Command: node src/postinstall.js
9:38:30 AM: Arguments:
9:38:30 AM: Directory: /opt/build/repo/node_modules/gatsby-telemetry
9:38:30 AM: Output:
9:38:30 AM: internal/modules/cjs/loader.js:638
9:38:30 AM:     throw err;
9:38:30 AM:     ^
9:38:30 AM: Error: Cannot find module './event-storage.js'
9:38:30 AM:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
9:38:30 AM:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
9:38:30 AM:     at Module.require (internal/modules/cjs/loader.js:692:17)
9:38:30 AM:     at require (internal/modules/cjs/helpers.js:25:18)
9:38:30 AM:     at Object.<anonymous> (/opt/build/repo/node_modules/gatsby-telemetry/src/postinstall.js:2:22)
9:38:30 AM:     at Module._compile (internal/modules/cjs/loader.js:778:30)
9:38:30 AM:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
9:38:30 AM:     at Module.load (internal/modules/cjs/loader.js:653:32)
9:38:30 AM:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
9:38:30 AM:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
9:38:30 AM: info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
9:38:32 AM: Error during Yarn install
9:38:32 AM: Error running command: Build script returned non-zero exit code: 1
9:38:32 AM: failed during stage 'building site': Build script returned non-zero exit code: 1
9:38:32 AM: Failing build: Failed to build site
9:38:32 AM: Finished processing build request in 1m12.189163395s
```

**Comment by briziel** [comment]
Should now work with gatsby-cli@2.7.24

**Comment by LucasLombardo** [comment]
Working for me now with the update, thanks @briziel

**Comment by geocine** [comment]
That was fast, thank you
