### ISSUE TITLE
Broken by recent changes

### ISSUE THREAD

**Issue by kurtharriger** [gatsbyjs/gatsby#132]
First time using gatsby just now and I was trying to follow the instructions to create a new project exactly following instructions in Usage section and all I got was a blank page.  I figured this was because I didn't specify a starter template, but after looking at the index.md I should have seen Welcome to your new Gatsby site.  No errors in dev console.  

I then tried the doc site and still got a blank page, but this time got error Uncaught TypeError: Router.createRoute is not a function in dev console.

I noticed the starter and doc templates changed just a few hours ago so I tried manually cloning the starter template and reverted back to version created in december and the site worked.  It appears the offending commit is:

https://github.com/gatsbyjs/gatsby-starter-default/commit/52fe75593ea1a47ff6e9a337dd871ccde685f3da

The doc-site template appears to have a similar set of changes.

**Comment by KyleAMathews** [comment]
Ack sorry about that. Working on new release and pushed the updates early
to the starter... should of put those on a branch.

**Comment by KyleAMathews** [comment]
Just released 0.8 🎉

Gatsby + starters are back in sync.
