### ISSUE TITLE
Gatsby V3: Error: "performance.mark  is not a function" on Safari <= 10.1

### ISSUE THREAD

**Issue by marcus13371337** [gatsbyjs/gatsby#32279]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Since we migrated to Gatsby V3 from V2 we have seen that a lot of our visitors are getting the following error `performance.mark is not a function` when visiting our site. It seems to be that `performance.mark` was introduced in Safari 10.2 (https://caniuse.com/?search=performance.mark)

### Reproduction Link

https://github.com/gatsbyjs/gatsby-starter-hello-world

### Steps to Reproduce

1. Visit a gatsby V3 site with Safari 10.1 or lower
2. Watch the error in the console
...

### Expected Result

Before  calling `performance.mark`  gatsby should check if that function exists (or add a polyfill for it), i.e not to throw an error when it doesn't exist

### Actual Result

An error is thrown

### Environment

```shell
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.6.3 - ~/.nvm/versions/node/v14.15.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 91.0.4472.114
    Safari: 14.1.1
  npmPackages:
    gatsby: 3.7.2 => 3.7.2 
    gatsby-plugin-google-marketing-platform: ^0.2.0 => 0.2.0 
    gatsby-plugin-image: ^1.7.1 => 1.7.1 
    gatsby-plugin-polyfill-io: ^1.1.0 => 1.1.0 
    gatsby-plugin-react-helmet: 4.7.1 => 4.7.1 
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.1 
    gatsby-plugin-robots-txt: ^1.6.2 => 1.6.2 
    gatsby-plugin-s3: ^0.3.8 => 0.3.8 
    gatsby-plugin-sass: 4.7.1 => 4.7.1 
    gatsby-plugin-sharp: 3.7.1 => 3.7.1 
    gatsby-plugin-sitemap: 2.12.0 => 2.12.0 
    gatsby-plugin-styled-components: 4.7.1 => 4.7.1 
    gatsby-plugin-ts-config: 1.1.5 => 1.1.5 
    gatsby-source-filesystem: 3.7.1 => 3.7.1 
    gatsby-transformer-sharp: 3.7.1 => 3.7.1 
    gatsby-transformer-yaml: 3.7.1 => 3.7.1
```

**Comment by marcus13371337** [comment]
Here is the failing line:
https://github.com/gatsbyjs/gatsby/blob/0d786693d99e1f0a035ab5b985082ad8a4242baa/packages/gatsby/cache-dir/production-app.js#L183

**Comment by herecydev** [comment]
Have you changed your browserslist? Gatsby will polyfill only what you specify or fall back to a defaults (which doesnt include Safari 10, hence you're experiencing that issue.

https://www.gatsbyjs.com/docs/how-to/custom-configuration/browser-support/#specify-what-browsers-your-project-supports-using-browserslist

**Comment by marcus13371337** [comment]
Could have missed that, this is our current browserlist in `package.json`:
```
  "browserslist": [
    ">0.25%",
    "IE 11",
    "not dead"
  ]
```

Tested it here:
https://browserslist.dev/?q=PjAuMjUlLCBJRSAxMSwgbm90IGRlYWQ%3D

It seems as you are right, Safari 10 is not supported according to our current browserlist. However, it seems as `Safari For IOS 9.3` and `Safari For IOS 10.3` should be covered by that browserlist. `performance.mark` is supported for ">= 11" Safari iOS according to caniuse, could it be something fishy there?

**Comment by herecydev** [comment]
That's not what I see locally;

```
and_chr 91
and_ff 89
and_uc 12.12       
android 4.4.3-4.4.4
chrome 91
chrome 90
chrome 89
chrome 87
chrome 85
edge 91
firefox 89
firefox 88
ios_saf 14.5-14.7
ios_saf 14.0-14.4
ios_saf 13.4-13.7
op_mini all
opera 76
safari 14.1
safari 14
safari 13.1
samsung 14.0
samsung 13.0
```

If you run it like `npx browserslist ">0.25%, not dead, not ie 11"` you will see exactly the same as what gatsby is actually going to use. I'm dubious of sites like you've linked, the versions aren't up-to-date, etc.

**Comment by marcus13371337** [comment]
Cool! Then there was no bug at all 😊 Thanks for your help! Have a nice end of the week!

**Comment by tu4mo** [comment]
This still happens even though my browserslist includes Safari from version 9 and up.

```
"browserslist": [
  "defaults",
  "chrome >= 42",
  "edge >= 12",
  "firefox >= 42",
  "ios_saf >= 9",
  "opera >= 35",
  "safari >= 9",
  "not ie 11"
]
```

**Comment by herecydev** [comment]
@tu4mo all those browser support the performance api though right? https://caniuse.com/mdn-api_performance

**Comment by tu4mo** [comment]
@herecydev Apparently not completely: [performance.mark](https://caniuse.com/mdn-api_performance_mark).

**Comment by tu4mo** [comment]
@LekoArts Could this be re-opened?

**Comment by yairau** [comment]
Hey @LekoArts,
It didn't solve the problem for me as well. 

Reproduction steps are almost the same as @marcus13371337 wrote:

1. Start with [gatsby-starter-hello-world](https://github.com/gatsbyjs/gatsby-starter-hello-world) 
2. Change `browserslist` config to: `"browserslist": [ ">0.1%", "safari>=9", "ios_saf>=9", "not dead" ],`
3. Visit the site on Safari 10.

The result is a blank page due to the error `performance.mark is not a function`.

Am I missing something?
Thanks!

**Comment by tu4mo** [comment]
Perhaps @wardpeet has some insights?

**Comment by herecydev** [comment]
Why don't you try and recreate with a simple script (using performance.mark) and run babel against it with your browserslist. If it's browserslist or babel not working correctly that will help identify what the correct solution is.

**Comment by herecydev** [comment]
Actually no, this can't be solved by polyfilling anyway. The fix is to check for it first, I'll put a PR in tonight.

**Comment by herecydev** [comment]
Okay should be fixed in the next gatsby version. @tu4mo you alright to comment if it's working for you when that's released?

**Comment by tu4mo** [comment]
@herecydev Sure thing!

**Comment by tu4mo** [comment]
Fixed in v3.12.0. Thanks @herecydev!
