### ISSUE TITLE
Gatsby Adapters causes regressions with headers & redirects for NETLIFY builds on >=5.12.0

### ISSUE THREAD

**Issue by techfg** [gatsbyjs/gatsby#38542]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

The forced usage of Gatsby Adapters has caused several regressions related to headers & redirects for builds running on NETLIFY.  As of v5.12.0, Gatsby will detect that the build is running on [NETLIFY](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/adapters.js#L17) and add the [gatsby-adapter-netlify](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/adapter/init.ts#L34) adapter to the build and remove the `gatsby-plugin-netlify` plugin without any `stock` way to "opt-out" of the behavior.

Unfortunately, the `gatsby-adapter-netlify` does not have feature parity with `gatsby-plugin-netlify` and also contains a few bugs.  The combination of these two things results in build output being different for anyone building on NETLIFY.

A couple of references to bugs/issues already filed:
1. https://github.com/gatsbyjs/gatsby/issues/38541
2. https://github.com/gatsbyjs/gatsby/issues/38538

After digging through the output and code some more, I believe this is a much broader set of issues than those two issues alone so creating this issue as an umbrella.  If the preference is to have a single issue for each individual item identified, please just let me know.

The issues discovered are:
1. [Headers on redirects](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-adapter-netlify/src/route-handler.ts#L84) are not emitted
2. `force` is not honored (needs to include `!`)
3. external redirects have a [forced `/` added](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/adapter/manager.ts#L279) to the beginning of them 
4. `Conditions` on redirects are not honored
5. The following features of `gatsby-plugin-netlify` are not available and therefore have no effect:
    1.  allPageHeaders
    2. transformHeaders
    3. mergeSecurityHeaders
    4. mergeCachingHeaders
    7. generateMatchPathRewrites
6. `Link` paths are not converted to their corresponding hash
7. Client-only routes have incorrect header

All of the above (and possibly some more I missed), will impact customers relying on any of these as soon as they build on Netlify with a version >= 5.12.0.

As mentioned [here](https://github.com/gatsbyjs/gatsby/pull/38520#issue-1881625777) as it relates to builds breaking, 5.12.0 likely should have been a major version update as all of these are breaking changes and since most likely have a semver of `^5.x.x`, customers relying on any of these features/functionality will be impacted if building on NETLIFY.

Most of the above issues are problems/missing functionality in the core Gatsby Adapter logic, not in the `gatsby-adapter-netlify` adapter itself.  For example, when [IRedirectRoute](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/adapter/manager.ts#L461) is created, `force` is not passed through so the adapter doesn't receive the value even though there is [code in the adapter](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-adapter-netlify/src/route-handler.ts#L90) to process it - same holds true for the `conditions` property.  Additionally, createRedirect allows for any set of `[key: string]: unknown` which aren't passed through (they wouldn't be used in this case but they should be passed through since [createRedirect API](https://github.com/gatsbyjs/gatsby/blob/db248ab1b7dfca7023816f53b4ebf1138468a9e2/packages/gatsby/index.d.ts#L1457) and  [IRedirectRoute](https://github.com/gatsbyjs/gatsby/blob/db248ab1b7dfca7023816f53b4ebf1138468a9e2/packages/gatsby/src/utils/adapter/types.ts#L47) support it.

I had created feature requests for the ability to [disable adapters](https://github.com/gatsbyjs/gatsby/discussions/38527) and add [allPageHeaders & transformHeaders](https://github.com/gatsbyjs/gatsby/discussions/38528), however the more that I've run up against, after thinking it through, I believe these aren't features but required given Adapters was a `minor` release version and not a major.  At the very least, adding a way to disable adapters as soon as possible is likely warranted.

In the meantime, for those that come across this, there are a couple of options to avoid the above issues:

1. Stay on a version of Gatsby < 5.12.0 - This is the simplest and recommended approach if any of the above would effect your site
2. Implement the [noop Adapter](https://github.com/gatsbyjs/gatsby/discussions/38527) solution that I describe in the discussion

I have created a full-set of repros that demonstrate three scenarios related to the output of headers & redirects - again, this only impacts builds on NETLIFY:

1. No Adapter - What the headers & redirects are when no adapter is used and `gatsby-plugin-netlify` is configured
- [main branch](https://github.com/techfg/gatsby-adapter-issues)
- [codesandbox](https://codesandbox.io/p/sandbox/gatsby-adapter-issues-no-adapter-forked-gqcv8g)
2. With Adapter - What the exact same site & config from #1 would generate for headers & redirects
- [with netlify adapter branch](https://github.com/techfg/gatsby-adapter-issues/tree/with-netlify-adapter)
- [codesandbox](https://codesandbox.io/p/sandbox/gatsby-adapter-issues-with-netlify-adapter-zn2cq8)
3. WIth Adapter & Gatsby Headers Config - As much as possible, use the `headers` config to replicate some of the functionality that is lost with Adapters compared to `gatsby-plugin-netlify`
 - [with netlify adapter and headeres config branch](https://github.com/techfg/gatsby-adapter-issues/tree/with-netlify-adapter-and-headers-config)
- [codesandbox](https://codesandbox.io/p/sandbox/gatsby-adapter-issues-with-netlify-adapter-and-header-config-fvdv6l)

Each branch as the following files in root directory:
1. sanitized_headers - The output of _headers after each respective build
2. sanitized_redirects - The output of _redirects after each respective build

I have manually adjusted these files from their original to align sort order some.  The output between using an adapter & gatsby-plugin-netlify is quite different (e.g., plug uses /*, adapter emits same headers for each path when /* is used) but hoping this makes it a little more readable.  You can review the [PRs](https://github.com/techfg/gatsby-adapter-issues/pulls) to see the differences between building with just `gatsby-plugin-netlify`

### Reproduction Link

https://github.com/techfg/gatsby-adapter-issues/tree/with-netlify-adapter-and-headers-config

### Steps to Reproduce

1. Run the build in all three branches and compare the output of `public/_headers` and `public/_redirects`

### Expected Result

The headers & redirects in a build that uses `gatsby-adapter-netlify` should be same as build using `gatsby-plugin-netlify` (or better in some cases like security improvements).

### Actual Result

The headers & redirects are not identical resulting in different build output without any changes to code/config of the site due to Adapters not being an "opt-in" feature.

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900HK
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.1/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.17.1/bin/npm
  Browsers:
    Chrome: 116.0.5845.179
  npmPackages:
    gatsby: ^5.11.0 => 5.12.4
    gatsby-adapter-netlify: ^1.0.0 => 1.0.0
    gatsby-plugin-netlify: ^5.1.0 => 5.1.0
  npmGlobalPackages:
    gatsby-cli: 5.12.1
```

### Config Flags

N/A

**Comment by zachmerrill** [comment]
I'm getting `error latestAdapters.find is not a function` almost every build on Netlify too. I keep having to clear my cache.

**Comment by techfg** [comment]
Found a couple more issues...

1) Changed title to `...causes regressions & issues...`
2) Added Issue 8 & 9

**Comment by laradevitt** [comment]
After upgrading one of our sites to 5.12.0:

(time period is between "clean" builds, about 26 days)

- "header rules processed" went from 0 to 563 
- cached dependencies went from 1.1 GB to 25.2 GB 
- build minutes from 2m50s to 14m9s

Yikes! Not sure where to go with this other than to downgrade...

**Comment by seanloock** [comment]
Ever since Netlify started automatically installing `gatsby-adapter-netlify` our custom Template page is being generated as `[...].html` instead of `index.html` resulting in a 404 when viewing page(s) from built site



The page is created in `gatsby-node.js` as follows
```
  const CheckoutPageTemplate = path.resolve(`src/templates/checkout.tsx`)
  createPage({
    path: process.env.GATSBY_PREFIX_PATH
      ? `${process.env.GATSBY_PREFIX_PATH}/checkout/`
      : "/checkout/",
    matchPath: process.env.GATSBY_PREFIX_PATH
      ? `${process.env.GATSBY_PREFIX_PATH}/checkout/*`
      : "/checkout/*",
    component: CheckoutPageTemplate,
  })
```


Can resolve this by renaming the `[...].html` file to `index.html` after generation or locking Gatsby to v5.10.0

However, both of these solutions are quite hacky and not ideal in long run

**Comment by henrik-m** [comment]
We were hit by this as well and only found this in production when we discovered that all URLs which supported clientside routes were delivered with 404 status codes instead of 200 when accessed via URL.

**Simple repro with latest versions of gatsby (5.13.1) and gatsby-adapter-netlify (1.1.1):**
Repository: https://gitlab.com/henrik-m/gatsby-redirect-bug-repro
Published Page: https://main--verdant-granita-458d34.netlify.app/en/settings/

The settings page (which is not even a client-only page) and all client-only pages below it respond with a 404 status code when directly accessed.

**Workaround: Downgrade to gatsby 5.11.x and gatsby-plugin netlify:**
Merge Request: https://gitlab.com/henrik-m/gatsby-redirect-bug-repro/-/merge_requests/1
Deploy Preview: https://deploy-preview-1--verdant-granita-458d34.netlify.app/en/settings/

The settings pages of the deploy preview are delivered with a 200 status code, as they should be.

**Comment by JamesToohey** [comment]
Adding our tale and some some keywords in here to help others, we were seeing builds intermittently failing on Netlify with Gatsby 5.12.

We had a JSON file imported in `gatsby-node.ts` that was being compiled by webpack (which can't be configured for this particular part of the build process...) at build time into `[name].[contenthash].js`, but when this file was accessed slightly later in the build process `contenthash` was entirely different, meaning the file couldn't be found.

Clearing the Netlify build cache solved this temporarily, but it appears that downgrading to 5.11 has resolved it. I have no idea if it's related to this plugin, but can't find a more relevant place to leave this comment and am unsure how to reproduce in order to open a separate issue.

**Comment by kakusio** [comment]
Query on redirects are not honored -> https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-adapter-netlify/src/route-handler.ts#L9C4-L9C9

`query = {redirect = "true"}`

Expected (behavior  on  Gatsby <v5.12)
```
/fake-path?redirect=true -> redirect
/fake-path -> 404
```

Current (behavior  on  Gatsby >=v5.12)
```
/fake-path?redirect=true -> redirect
/fake-path -> redirect
```

**Comment by olivier5741** [comment]
Hi, I'm also experiencing issues with the netlify adapter. The data for the website comes from mongoDB through the plugin. 

I configure the relationships between collections in `gatsby-node.ts` with `createSchemaCustomization` but after I installed the adapter, **property inference doesn't seem to work anymore** ... I was configuring the mongo id and foreign keys then letting gatsby automatically infer the rest but it doesn't seem to work any more : I get loads of graphQL validation issues ...

```typescript
exports.createSchemaCustomization = ({ actions }: any) => {
  const { createTypes } = actions;

  // id creation
  const mongoIdTypeDefs = collections
    .map(
      (c) =>
        `type mongodb${capitalizeFirstLetter(c)} implements Node {
            _id: String @proxy(from: "mongodb_id")
        }`
    )
    .join("\n");

  createTypes(mongoIdTypeDefs);

  const typeDefs1 = `
      type mongodbActivities implements Node {
        place: mongodbPlaces @link(by: "mongodb_id")
        profiles: [mongodbProfiles] @link(by: "mongodb_id")
        contacts: [mongodbContacts] @link(by: "mongodb_id")
      }
      type mongodbCounters implements Node {
        catalog: mongodbCatalogs @link(by: "mongodb_id")
        place: mongodbPlaces @link(by: "mongodb_id")
        profiles: [mongodbProfiles] @link(by: "mongodb_id")
        actions: [mongodbActions] @link(by:"subject.counter", from: "mongodb_id")
     }
    //  ...
    `;
  createTypes(typeDefs1);
};

exports.createPages = async function ({ actions, graphql }: any) {
  const { data: marketplacesQuery } = await graphql(`
    query {
      allMongodbCounters(filter: { type: { eq: "marketplace" } }) {
        nodes {
          _id
          name
        }
      }
    }
  `);
  marketplacesQuery.allMongodbCounters.nodes.forEach((node: any) => {
    const _id = node._id;
    const component = path.resolve(`./src/templates/marketplace.tsx`);

    actions.createPage({
      path: "/marketplace/" + _id,
      component: component,
      context: { id: _id },
    });
  });
```
