### ISSUE TITLE
Cannot find module 'gatsby-page-utils/apply-trailing-slash-option' since Gatsby 4.7

### ISSUE THREAD

**Issue by soniCaH** [gatsbyjs/gatsby#34784]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Since I upgraded the gatsby monorepo to 4.7.1 my jest tests seems to break:

`Cannot find module 'gatsby-page-utils/apply-trailing-slash-option' from 'node_modules/gatsby-link/rewrite-link-path.js'`

Full error message:

```  ● Test suite failed to run

    Cannot find module 'gatsby-page-utils/apply-trailing-slash-option' from 'node_modules/gatsby-link/rewrite-link-path.js'

    Require stack:
      node_modules/gatsby-link/rewrite-link-path.js
      node_modules/gatsby-link/index.js
      node_modules/gatsby/cache-dir/commonjs/gatsby-browser-entry.js
      __mocks__/gatsby.js
      src/components/player--featured.js
      src/components/__tests__/player--featured.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (node_modules/gatsby-link/rewrite-link-path.js:8:33)
```

I tried adding the new trailingSlashes option to my config, but it did not fix it.

### Reproduction Link

https://github.com/soniCaH/KCVV-Elewijt-Gatsby/pull/657

### Steps to Reproduce

1. yarn install
2. yarn run test

### Expected Result

Jest tests pass like on Gatsby 4.6.x

### Actual Result

Jest test don't pass (locally / circleci) - https://app.circleci.com/pipelines/github/soniCaH/KCVV-Elewijt-Gatsby/1934/workflows/f5494c77-ea58-4f85-9582-c8ca87a3c2b4/jobs/1910

### Environment

```shell
System:
    OS: macOS 11.6
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.4.0 - /usr/local/bin/node
    Yarn: 1.22.15 - ~/.yarn/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 98.0.4758.80
    Firefox: 96.0.1
    Safari: 15.3
  npmPackages:
    gatsby: 4.7.1 => 4.7.1 
    gatsby-cli: 4.7.0 => 4.7.0 
    gatsby-paginate: 1.1.1 => 1.1.1 
    gatsby-plugin-google-tagmanager: 4.7.0 => 4.7.0 
    gatsby-plugin-image: 2.7.0 => 2.7.0 
    gatsby-plugin-manifest: 4.7.0 => 4.7.0 
    gatsby-plugin-netlify: next => 4.0.0-next.0 
    gatsby-plugin-offline: 5.7.0 => 5.7.0 
    gatsby-plugin-sass: 5.7.0 => 5.7.0 
    gatsby-plugin-sharp: 4.7.0 => 4.7.0 
    gatsby-plugin-use-query-params: 1.0.1 => 1.0.1 
    gatsby-source-drupal: 5.7.0 => 5.7.0 
    gatsby-source-filesystem: 4.7.0 => 4.7.0 
    gatsby-transformer-sharp: 4.7.0 => 4.7.0 
  npmGlobalPackages:
    gatsby-cli: 2.8.14
    gatsby: 2.18.5
```

### Config Flags

FAST_DEV: true

**Comment by LekoArts** [comment]
Hi!

Please see the release notes here: https://www.gatsbyjs.com/docs/reference/release-notes/v4.7/#trailingslash-option

> If you’re unit testing gatsby-link you’ll need to update the moduleNameMapper option to include gatsby-page-utils, see [Unit Testing documentation](https://www.gatsbyjs.com/docs/how-to/testing/unit-testing/#2-creating-a-configuration-file-for-jest) for more details.

You'll want to add `"^gatsby-page-utils/(.*)$": "gatsby-page-utils/dist/$1"` to `moduleNameMapper` to workaround the issue https://github.com/facebook/jest/issues/9771
