### PR TITLE
fix(gatsby): Update `loader.loadPage` to return a Promise on error

### PR DESCRIPTION
**Pull request by markacola**
## Description

Quite a few places, including the [EnsureResources.loadResources method](https://github.com/gatsbyjs/gatsby/blob/5c22948094d98f3d4ea90253c80fc78d9f53cc20/packages/gatsby/cache-dir/ensure-resources.js#L40), assume that the [loader.loadPage](https://github.com/gatsbyjs/gatsby/blob/b346071eaf14b53fd6dd58c3f270c2f8a964ef3e/packages/gatsby/cache-dir/loader.js#L344) returns a promise, and explicitly using the `.then` method instead of async/await syntax.

One of the [error code path](https://github.com/gatsbyjs/gatsby/blob/b346071eaf14b53fd6dd58c3f270c2f8a964ef3e/packages/gatsby/cache-dir/loader.js#L350) in this method return a plain object, resulting in errors such as:
```
(...).loadPage(...).then is not a function
```

The noticeable effect of this for me was a link navigation failure on the first click (similar to the behaviour noted in #18866 and #34251).
I have been unable to reproduce this exact behaviour consistently, but I noted the experience while smoke testing just after a deploy and the error was reported to Sentry.io from my site (clicking "Services" in the navbar https://www.doomsdaytuna.com/).

I considered changing the `loadPage` method to an `async` function, however that would be a larger change, and doesn't follow the current conventions of the class. I also didn't think that `Promise.reject` would be suitable, given this path is expected to return a failure object.

This change seem minimal, and ensures the function is always returning a Promise.

### Documentation

N/A

## Related Issues

Addresses #34251 partially, as it will surface the error object now, instead of erroring on the call to the undefined `.then`.
Behaviour may be related to #18866, i.e. reproducible between deploys.

Keen to hear any feedback. Thanks!

### CODE REVIEW

**Review by LekoArts — APPROVED** [review]
Thanks!
