### ISSUE TITLE
Build fails after updating gatsby-plugin-sharp from 3.0.1 to 3.1.2

### ISSUE THREAD

**Issue by GayaneKasparova** [gatsbyjs/gatsby#30484]
## Description

Build fails after updating gatsby-plugin-sharp from 3.0.1 to 3.1.2

 Error: Cannot find module 'gatsby-core-utils'
1:00:49 PM:   Require stack:
1:00:49 PM:   - /opt/build/repo/node_modules/babel-plugin-remove-graphql-queries/index.js
1:00:49 PM:   - /opt/build/repo/node_modules/gatsby/dist/query/file-parser.js
1:00:49 PM:   - /opt/build/repo/node_modules/gatsby/dist/query/query-compiler.js
1:00:49 PM:   - /opt/build/repo/node_modules/gatsby/dist/query/query-watcher.js
1:00:49 PM:   - /opt/build/repo/node_modules/gatsby/dist/services/extract-queries.js
1:00:49 PM:   - /opt/build/repo/node_modules/gatsby/dist/services/index.js
1:00:49 PM:   - /opt/build/repo/node_modules/gatsby/dist/bootstrap/index.js
1:00:49 PM:   - /opt/build/repo/node_modules/gatsby/dist/commands/build.js
1:00:49 PM:   - /opt/build/repo/node_modules/gatsby-cli/lib/create-cli.js
1:00:49 PM:   - /opt/build/repo/node_modules/gatsby-cli/lib/index.js
1:00:49 PM:   - /opt/build/repo/node_modules/gatsby/dist/bin/gatsby.js
1:00:49 PM:   - /opt/build/repo/node_modules/gatsby/cli.js

### Environment

  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.5 - C:\Python38\python.EXE
  Browsers:
    Chrome: 89.0.4389.90
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.57)
  npmPackages:
    gatsby: ^3.1.2 => 3.1.2
    gatsby-cli: ^3.1.0 => 3.1.0
    gatsby-plugin-google-analytics: ^3.1.0 => 3.1.0
    gatsby-plugin-graphql-codegen: ^2.7.1 => 2.7.1
    gatsby-plugin-image: ^1.1.2 => 1.1.2
    gatsby-plugin-manifest: ^3.1.0 => 3.1.0
    gatsby-plugin-netlify: ^3.1.0 => 3.1.0
    gatsby-plugin-offline: ^4.1.0 => 4.1.0
    gatsby-plugin-react-helmet: ^4.1.0 => 4.1.0
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-robots-txt: ^1.5.5 => 1.5.5
    gatsby-plugin-sharp: ^3.1.2 => 3.1.2
    gatsby-plugin-sitemap: ^3.1.0 => 3.1.0
    gatsby-plugin-styled-components: ^4.1.0 => 4.1.0
    gatsby-plugin-typescript: ^3.1.0 => 3.1.0
    gatsby-source-datocms: ^2.6.6 => 2.6.6
    gatsby-source-filesystem: ^3.1.0 => 3.1.0
    gatsby-transformer-remark: ^3.1.0 => 3.1.0
    gatsby-transformer-sharp: ^3.1.0 => 3.1.0
  npmGlobalPackages:
    gatsby-cli: 2.7.31

**Comment by vladar** [comment]
Can you check what is the version of `babel-plugin-remove-graphql-queries` package and where it comes from?

With yarn run:
```sh
yarn why babel-plugin-remove-graphql-queries
``` 

or with npm:
```sh
npm ls babel-plugin-remove-graphql-queries
```

Also does removing node_modules and yarn.lock (or package-lock.json with npm) and reinstalling help?
